spring.application.name=tinder-with-ai-backend
spring.ai.openai.api-key=
spring.ai.openai.chat.options.model=gpt-4o
spring.ai.openai.chat.options.temperature=0.5
tinderai.lookingForGender=woman

startup-actions.initializeProfiles=true
tinderai.character.user.id=user
tinderai.character.user.firstName=Dinesh
tinderai.character.user.lastName=Gunnala
tinderai.character.user.age=25
tinderai.character.user.ethnicity=Indian
tinderai.character.user.gender=MALE
tinderai.character.user.bio=Software engineer and learner. I like reading and making things.
tinderai.character.user.imageUrl=
tinderai.character.user.myersBriggsPersonalityType=INTP

